app_flask_login_alternative_JWT_token/main.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from flask_jwt_extended import jwt_required, get_current_user
from db import db
import datetime

main = Blueprint('main', __name__)


@main.route('/')
def index():
    if current_user.is_authenticated:
        # writing user request to database
        current_user.last_request_at = datetime.datetime.now()
        db.session.commit()
    return render_template('index.html')

@main.route('/profile')
#@login_required
@jwt_required()
def profile():
    # writing user request to database
    current_user.last_request_at = datetime.datetime.now()
    db.session.commit()
    return render_template('profile.html', username=current_user.username)

app_flask_login_alternative_JWT_token/posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for

from models import Post
from forms import PostForm

from db import db

import datetime


from flask_login import login_required, current_user
from flask_jwt_extended import jwt_required, get_current_user

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
#@login_required
@jwt_required()
def post_create():
    form = PostForm()
    
    if request.method == "POST":
        title = request.form.get('title')
        body = request.form.get('body')
        
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print("Veryy long traceback")
        return redirect(url_for('posts.post_detail', slug=post.slug))
    
    # writing user request to database
    current_user.last_request_at = datetime.datetime.now()
    db.session.commit()
    
    return render_template('posts/post_create.html', form=form)

@posts.route('/')
def posts_list():
    op = request.args.get('op')
    
    if op:
        posts = Post.query.filter(Post.title.contains(op) |
        Post.body.contains(op))
    else:
        posts = Post.query.order_by(Post.created.desc())
    return render_template('posts/posts.html', posts=posts)
    
    posts = Post.query.all()
    
    if current_user.is_authenticated:
        # writing user request to database
        current_user.last_request_at = datetime.datetime.now()
        db.session.commit()
    
    return render_template('posts/posts.html', posts=posts)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    
    if current_user.is_authenticated:
        # writing user request to database
        current_user.last_request_at = datetime.datetime.now()
        db.session.commit()
    
    return render_template('posts/post_detail.html', post=post)

@posts.route('/like/<int:post_id>/<action>')
#@login_required
@jwt_required()
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        if post.today != str(datetime.date.today()):
            post.today = str(datetime.date.today())
            post.likes_today = 0
        
        post.likes_today +=1
        current_user.like_post(post)
        current_user.last_request_at = datetime.datetime.now()
        db.session.commit()
    if action == 'unlike':
        post.likes_today -=1
        current_user.unlike_post(post)
        current_user.last_request_at = datetime.datetime.now()
        db.session.commit()
    return redirect(request.referrer)

app_flask_login_alternative_JWT_token/templates/base (another copy).html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
		<div class="navbar-end">
		    <a href="{{ url_for('main.index') }}" class="navbar-item">
		        Home
		    </a>
		    {% if current_user.is_authenticated %}
		    <a href="{{ url_for('main.profile') }}" class="navbar-item">
		        Profile
		    </a>
		    {% endif %}
		    {% if not current_user.is_authenticated %}
		    <a href="{{ url_for('auth.login') }}" class="navbar-item">
		        Login
		    </a>
		    <a href="{{ url_for('auth.signup') }}" class="navbar-item">
		        Sign Up
		    </a>
		    {% endif %}
		    {% if current_user.is_authenticated %}
		    <a href="{{ url_for('auth.logout') }}" class="navbar-item">
		        Logout
		    </a>
		    {% endif %}
		</div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app_flask_login_alternative_JWT_token/templates/base (copy).html
<!doctype html>
<head>
{% block header %}{% endblock %}
<title>{% block title %}{% endblock %}</title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index')}}">Flask Blog App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('posts.posts_list')}}">Blog Home</a>
        </li>
        
          <a class="nav-link" href="{{ url_for('posts.post_create')}}">New Post</a>
        
        <a class="nav-link active" aria-current="page" href="/sign_up">Sign up</a>
        <a class="nav-link active" aria-current="page" href="/login">Login</a>
        <a class="nav-link active" aria-current="page" href="/logout">Logout</a>

        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" name='op' aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</body>

<div class="container">
	<div class="row">
		<div class="col-8 mx-auto">
		{% block content %}{% endblock %}
		</div>
	</div>
</div>

<section class="content">
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
</section>

app_flask_login_alternative_JWT_token/templates/base.html
<!doctype html>
<head>
{% block header %}{% endblock %}
<title>{% block title %}{% endblock %}</title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index')}}">Flask Blog App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('posts.posts_list')}}">Blog Home</a>
        </li>
        
	{% if current_user.is_authenticated %}
	<a class="nav-link" href="{{ url_for('posts.post_create')}}">New Post</a>
	<a class="nav-link active" href="{{ url_for('main.profile') }}" >Profile</a>
	<a class="nav-link active" aria-current="page" href="/logout">Logout</a>
	{% endif %}
          
          
	{% if not current_user.is_authenticated %}    
        <a class="nav-link active" aria-current="page" href="/signup">Sign up</a>
        <a class="nav-link active" aria-current="page" href="/login">Login</a>
        {% endif %}
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" name='op' aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</body>

<div class="container">
	<div class="row">
		<div class="col-8 mx-auto">
		{% block content %}{% endblock %}
		</div>
	</div>
</div>

<section class="content">
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
</section>

app_flask_login_alternative_JWT_token/templates/index.html
{% extends "base.html" %}

{% block title %}
Index
{% endblock %}

{% block content %}

<body>
    <h3>This is Index page</h3>
    <p>Welcome to our blog app. You can visit <a href="/blog/">Blog Home.</a></p>
</body>


{% endblock %}

app_flask_login_alternative_JWT_token/templates/index22.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

app_flask_login_alternative_JWT_token/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
    
    	{% with messages = get_flashed_messages() %}
	{% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
	{% endif %}
	{% endwith %}

        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class='form-control' type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class='form-control' type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="btn btn-outline-success">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app_flask_login_alternative_JWT_token/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ username }}!
</h1>
{% endblock %}

app_flask_login_alternative_JWT_token/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
    
    	{% with messages = get_flashed_messages() %}
	{% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
    </div>
	{% endif %}
	{% endwith %}

        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class='form-control' type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class='form-control' type="text" name="username" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class='form-control' type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="btn btn-outline-success">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}